services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8000
      - NODE_ENV=production
    depends_on:
      backend:
        condition: service_started
    restart: unless-stopped
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    environment:
      - SECRET_KEY=${SECRET_KEY:-yoursecretkeyhere}
      - ENVIRONMENT=production
    restart: unless-stopped
    networks:
      - app-network

  # Optional: Firebase Auth Emulator for local development
  auth-emulator:
    image: andreysenov/firebase-tools:latest
    command: firebase emulators:start --only auth
    ports:
      - "9099:9099"
    volumes:
      - ./.firebase:/home/node/.firebase
    networks:
      - app-network
    profiles:
      - dev

networks:
  app-network:
    driver: bridge 