"""Add missing fields to cover_letters table

Revision ID: c3267ee127fd
Revises: 4f13ae5172a7
Create Date: 2025-04-21 04:01:37.290916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3267ee127fd'
down_revision: Union[str, None] = '4f13ae5172a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add columns as nullable first
    op.add_column('cover_letters', sa.Column('job_title', sa.String(length=255), nullable=True))
    op.add_column('cover_letters', sa.Column('tone', sa.String(length=50), nullable=True))
    op.add_column('cover_letters', sa.Column('max_length', sa.Integer(), nullable=True))
    
    # Update existing records with default values
    op.execute("UPDATE cover_letters SET job_title = 'Not specified' WHERE job_title IS NULL")
    op.execute("UPDATE cover_letters SET tone = 'professional' WHERE tone IS NULL")
    op.execute("UPDATE cover_letters SET max_length = 500 WHERE max_length IS NULL")
    
    # Now make job_title non-nullable
    op.alter_column('cover_letters', 'job_title', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cover_letters', 'max_length')
    op.drop_column('cover_letters', 'tone')
    op.drop_column('cover_letters', 'job_title')
    # ### end Alembic commands ###